/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eff0fa",
        "error": "#ba1a1a",
        "primary": "#0058be",
        "on-surface-variant": "#424754",
        "surface-container-highest": "#e1e2ec",
        "on-error-container": "#93000a",
        "on-primary-container": "#fefcff",
        "tertiary-fixed-dim": "#bec6e0",
        "tertiary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e7f2",
        "tertiary-container": "#6c748b",
        "on-background": "#191b23",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fefcff",
        "surface-bright": "#f9f9ff",
        "surface-container-low": "#f2f3fd",
        "on-error": "#ffffff",
        "inverse-primary": "#adc6ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001a42",
        "surface-variant": "#e1e2ec",
        "background": "#f9f9ff",
        "tertiary": "#545c72",
        "surface-container": "#ecedf7",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-dim": "#d8d9e3",
        "secondary-fixed-dim": "#b7c8e1",
        "primary-container": "#2170e4",
        "on-secondary-fixed": "#0b1c30",
        "secondary-fixed": "#d3e4fe",
        "secondary-container": "#d0e1fb",
        "secondary": "#505f76",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3038",
        "on-surface": "#191b23",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary-container": "#54647a",
        "primary-fixed": "#d8e2ff",
        "outline-variant": "#c2c6d6",
        "outline": "#727785",
        "on-tertiary-fixed": "#131b2e",
        "surface-tint": "#005ac2",
        "surface": "#f9f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "card_padding": "16px",
        "gutter": "24px",
        "lane_width": "320px",
        "margin": "32px",
        "unit": "4px",
        "xl": "40px",
        "lg": "24px",
        "md": "16px",
        "sm": "8px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
